# Generated by Django 3.2 on 2021-04-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_nom', models.CharField(max_length=60)),
                ('D_prénom', models.CharField(max_length=70)),
                ('D_naiss', models.DateField(blank=True, null=True)),
                ('spécialité', models.CharField(max_length=40)),
                ('éducation', models.TextField(max_length=250)),
                ('Diplôme', models.TextField(max_length=250)),
                ('expérience_professionnelle', models.TextField(max_length=250)),
                ('D_adresse', models.TextField()),
                ('N_téléphone', models.IntegerField()),
                ('D_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('prénom', models.CharField(max_length=70)),
                ('naiss', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(max_length=20)),
                ('etatCivil', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=80)),
                ('téléphone', models.IntegerField()),
                ('adresse', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
