# Generated by Django 3.2 on 2021-04-06 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancer_type', models.CharField(max_length=120)),
                ('pdf_files', models.FileField(upload_to='')),
                ('scanner_type', models.CharField(max_length=140)),
                ('scanner_files', models.ImageField(upload_to='')),
                ('PatKey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.patient')),
            ],
        ),
    ]
