# Generated by Django 3.2 on 2021-04-06 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalFiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalfiles',
            old_name='PatKey',
            new_name='Patient',
        ),
    ]
